### ISSUE TITLE
Optimize collapse of nav bar

### ISSUE THREAD

**Issue by danpia** [evvvritt/chen-williams#11]
Add these additional break points, since 25% is too high for bigger screens:
- [ ] 760px - 1024px collapses 33%
- [ ] 1025px - 1900px collapses 40%
- [ ] >= 1900px collapses 33%

**Comment by evvvritt** [comment]
Hm, looks like the -50% above 1280px got lost – just redeployed. Take a look and confirm any adjustments

**Comment by danpia** [comment]
yep, looks good
