### ISSUE TITLE
Wrap images in additional div for blurring glitch?

### ISSUE THREAD

**Issue by danpia** [evvvritt/chen-williams#14]
The 103% percentage kind of works, but for landscape images isn't the best solution. Would wrapping the <img> with a div help having a clean edge like the top and left sides here?
![screenshot 2018-03-21 17 37 35_preview](https://user-images.githubusercontent.com/3718189/37738951-0655a144-2d2f-11e8-9808-de21efdffee3.png)

**Comment by evvvritt** [comment]
Ah, yeah maybe - will try

**Comment by evvvritt** [comment]
Diff solution but improved – image is scaled 105% but can squeak smaller if desired. Will see on next push
