### ISSUE TITLE
Newsletter form

### ISSUE THREAD

**Issue by danpia** [evvvritt/chen-williams#19]
- [x] on main view add this button, on click it just opens Info layer
- [x] text of the button should be editable from Prismic

![screenshot 2018-04-03 11 19 08_preview](https://user-images.githubusercontent.com/3718189/38258629-fe6936f6-3730-11e8-86b9-7598562f7039.png)

Just for size reference this is how I roughly styled it on Inspector:
```
element.style {
    bottom: 20px;
    right: 20px;
    background-color: #fff;
    border: 1px solid #000;
    border-radius: 13px;
    height: 1em;
    line-height: 0.4em;
    padding: 0.5em 1em 1em 1.2em;
}
```

- [x] on Info add the input field, only the sentence above should be editable
- [x] you can probably grab the field code here http://chen-williams.com/info (if not I'll ask)
![screenshot 2018-04-03 12 49 24_preview](https://user-images.githubusercontent.com/3718189/38263237-8f91dfd2-373d-11e8-9d5b-a5ec61f68e19.png)

**Comment by evvvritt** [comment]
Ok, now editable/hideable in Prismic
