### ISSUE TITLE
Currently hard to select a sub-category in the mobile menu 

### ISSUE THREAD

**Issue by danpia** [evvvritt/chen-williams#21]
- [ ] let me know if you have a better idea for how the selection process on mobile menu could work, otherwise probably something like this:

1.  "shop - everything" by default
2. open menu: current page is shown as selected
3. tap on top category, i.e. Furniture: sub-categories of Furniture appear **unselected**
4. tap on sub-category: menu closes 

- [x] when menu is closed, tapping on any top category or sub-category in the navigation should open the menu.

**Comment by evvvritt** [comment]
Number 3 incomplete

**Comment by evvvritt** [comment]
Ok, pushed. "Everything" always starts selected since it's immediately active when category/URL changes. Hope that's okay? Any subsequent sub-filter click closes the menu.

**Comment by danpia** [comment]
yep that works
