### ISSUE TITLE
Padding on Close square triggers closing action

### ISSUE THREAD

**Issue by danpia** [evvvritt/chen-williams#31]
Clicking that area will close the product, risk of closing when you're clicking the slideshow:

![screenshot 2018-05-04 11 09 16_preview](https://user-images.githubusercontent.com/3718189/39635518-bca4c8de-4f8b-11e8-9c55-980cac1aefc7.png)

**Comment by evvvritt** [comment]
Ok, cursor should pass through to slideshow if not over a link now [pushed]
