### ISSUE TITLE
Portrait images on mobile slideshow overlap description

### ISSUE THREAD

**Issue by danpia** [evvvritt/chen-williams#33]
![0-1](https://user-images.githubusercontent.com/3718189/40309970-53a47a9a-5cd9-11e8-8d37-e8df9524fe15.png)

Easiest solutions seems to be:
- move the description down one more block 
- vertical-center align the image 
- just crop it overflow-y

**Comment by evvvritt** [comment]
what if we scale to fit inside square frame, left-aligned? would mean there's a gap between the next image but...

**Comment by danpia** [comment]
yes that works
