### ISSUE TITLE
Solution for breadcrumbs in this case

### ISSUE THREAD

**Issue by danpia** [evvvritt/chen-williams#4]
<img width="1349" alt="screen shot 2018-02-16 at 4 08 31 pm" src="https://user-images.githubusercontent.com/3718189/36335315-dce2a7a4-1333-11e8-9d9d-94281ed632a5.png">

**Comment by evvvritt** [comment]
was thinking we could add an empty button + stem if the submenu doesn't
reach all the way?

**Comment by danpia** [comment]
@evvvritt I think just stem without button looks good:
<img width="924" alt="screen shot 2018-02-21 at 4 59 03 pm" src="https://user-images.githubusercontent.com/3718189/36507785-c38886e0-1728-11e8-9d3a-39f45361530f.png">
