### ISSUE TITLE
Slide/play behavior when a video is present

### ISSUE THREAD

**Issue by danpia** [evvvritt/chen-williams#7]
- any time the video is in the "active" viewport position (left) will start playing, including if slideshow starts with a video
- clicking the video surface won't make it play/pause, just slide. 
- when a video is playing pause button (svg attached) appears 

[CHE-pause.zip](https://github.com/evvvritt/chen-williams/files/1800836/CHE-pause.zip)

**Comment by evvvritt** [comment]
@danpia – So, Safari (first iOS and [now Mac](https://webkit.org/blog/7734/auto-play-policy-changes-for-macos/)) now doesn't allow autoplay unless they're muted, by default. Do you still want to autoplay (and maybe show an unmute button)?

**Comment by danpia** [comment]
Let's disallow autoplay and have play button if the slideshow starts with a video. 
Can we trigger play if instead is not on first position, after you slide it to active position?

**Comment by evvvritt** [comment]
Yep, but in Safari no video will autoplay if it's not muted. I can manually mute it from the start (and we provide an unmute button). Or we simply show play button if autoplay isn't allowed.

Does that make sense?

**Comment by danpia** [comment]
yes, let's play it muted with unmute button then. I'll send the svg

**Comment by danpia** [comment]
icons: [mute-sound.zip](https://github.com/evvvritt/chen-williams/files/1816215/mute-sound.zip)

**Comment by evvvritt** [comment]
Pushed:
– video autoplays if first slide
– videos play when active slide (pause when not)
– videos muted by default (icon bottom right corner?)
– clicking video: (on desktop) next slide, (on mobile) play/pause video 
– icons: (non-touch) show on hover, (touch) always visible
